"""empty message

Revision ID: 4acbb8854131
Revises: 94ebaaf72085
Create Date: 2020-01-03 01:23:00.789812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4acbb8854131'
down_revision = '94ebaaf72085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_access_token')
    op.drop_table('token_blacklist')
    op.drop_table('user_refresh_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refresh_token',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('revoked', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('refresh_token', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'revoked'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('token_blacklist',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('jti', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('token_type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('user_identity', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('expires', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('user_access_token',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('revoked', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('access_token', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'revoked'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
