"""empty message

Revision ID: e0f979b52c56
Revises: a1daa6ac7c0e
Create Date: 2020-01-02 17:44:42.095755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0f979b52c56'
down_revision = 'a1daa6ac7c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
